# Generated by Django 3.0 on 2021-06-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(height_field='Height', upload_to='', width_field='Width')),
                ('Height', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(height_field='Height', upload_to='', width_field='Width')),
                ('Height', models.IntegerField(blank=True, default=0, null=True)),
                ('Width', models.IntegerField(blank=True, default=0, null=True)),
                ('Body', models.TextField()),
                ('Slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Skill_Range', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
