# Generated by Django 3.0 on 2021-06-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210607_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='Publish',
            field=models.BooleanField(default=False),
        ),
    ]
