# Generated by Django 3.0 on 2021-06-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210611_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Is_Published',
            new_name='Published',
        ),
    ]
