# Generated by Django 3.0 on 2021-06-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210611_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Published',
            new_name='Publish',
        ),
    ]
