# Generated by Django 3.0 on 2021-06-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210611_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
