# Generated by Django 3.0 on 2021-06-13 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='Skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Skill'),
        ),
        migrations.AlterField(
            model_name='about',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='image/about'),
        ),
    ]
