# Generated by Django 3.0 on 2021-06-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210613_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='Skill',
        ),
        migrations.AddField(
            model_name='gallery',
            name='Skill',
            field=models.ManyToManyField(blank=True, null=True, to='home.Skill'),
        ),
    ]
