# Generated by Django 3.0 on 2021-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210620_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Readed',
            field=models.BooleanField(default=False),
        ),
    ]
