# Generated by Django 3.0 on 2021-06-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contact_readed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='updated',
            new_name='Updated',
        ),
    ]
