# Generated by Django 3.0 on 2021-06-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210620_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Image',
            field=models.ImageField(height_field='Height', upload_to='image/<function Upload_Location at 0x000001D56D10AC10>/', width_field='Width'),
        ),
    ]
