# Generated by Django 3.0 on 2021-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210621_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Image',
            field=models.ImageField(height_field='Height', upload_to='image/gallery', width_field='Width'),
        ),
    ]
