# Generated by Django 3.0 on 2021-06-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210621_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
    ]
